# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tictactoe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ended', models.BooleanField(default=False)),
                ('turn', models.SmallIntegerField(default=0)),
                ('board', tictactoe.models.ListField(default=[0, 0, 0, 0, 0, 0, 0, 0, 0], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('lastActive', models.DateTimeField(default=datetime.datetime(2016, 4, 10, 0, 39, 44, 495570), verbose_name=b'Last Active')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='tictactoe.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='tictactoe.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tictactoe.Player'),
        ),
    ]
